name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ⬣ Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: 📥 Install deps
        run: pnpm install

#      - name: 🔬 Lint
#        run: pnpm run lint

#  typecheck:
#    name: ʦ Types
#    runs-on: ubuntu-latest
#    steps:
#      - name: ⬇️ Checkout repo
#        uses: actions/checkout@v4
#
#      - uses: pnpm/action-setup@v3
#        name: Install pnpm
#        with:
#          version: 9
#          run_install: false
#
#      - name: ⎔ Setup node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 22.9.0
#
#      - name: 📥 Install deps
#        run: pnpm install
#
#      - name: 🔎 Type check
#        run: pnpm run typecheck

#  test:
#    name: ⚡ Test
#    runs-on: ubuntu-latest
#    steps:
#      - name: ⬇️ Checkout repo
#        uses: actions/checkout@v4
#
#      - uses: pnpm/action-setup@v3
#        name: Install pnpm
#        with:
#          version: 9
#          run_install: false
#
#      - name: ⎔ Setup node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 22.9.0
#
#      - name: 📥 Install deps
#        run: pnpm install
#
#      - name: ⚡ Run vitest
#        run: pnpm run test
#
#  e2e:
#    name: 🎭 E2E
#    runs-on: ubuntu-latest
#    steps:
#      - name: ⬇️ Checkout repo
#        uses: actions/checkout@v4
#
#      - uses: pnpm/action-setup@v3
#        name: Install pnpm
#        with:
#          version: 9
#          run_install: false
#
#      - name: ⎔ Setup node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 22.9.0
#
#      - name: 📥 Install deps
#        run: pnpm install
#
#      - name: 🌐 Install browsers
#        run: pnpm playwright install chromium
#
#      - name: 🎭 Run e2e tests
#        run: pnpm run e2e

  publish-client:
    name: 🚀 Publish client
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: [lint, typecheck, test, e2e]
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: 📥 Install deps
        run: pnpm install

      - name: ⚙️ Build
        run: pnpm build

      - name: 🚀 Publish client
        run: pnpm run client deploy:prod

  publish-server:
    name: 🚀 Publish server
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    needs: [lint, typecheck, test, e2e]
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.9.0

      - name: 📥 Install deps
        run: pnpm install

      - name: ⚙️ Build
        run: pnpm build

      - name: 🚀 Publish server
        run: pnpm run server deploy:prod
