name: Pre-deploy Migration
on:
  push:
    branches: [main]
    paths:
      - 'apps/server/src/db/migrations/*.sql'

jobs:
  migrate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/server

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        run: npm run db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Railway will deploy automatically after this completes